//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiveLearning.FormClient.StudentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseDTO", Namespace="http://schemas.datacontract.org/2004/07/ActiveLearning.ServiceInterfaces.DTO")]
    [System.SerializableAttribute()]
    public partial class CourseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DeleteDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateDTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDT {
            get {
                return this.CreateDTField;
            }
            set {
                if ((this.CreateDTField.Equals(value) != true)) {
                    this.CreateDTField = value;
                    this.RaisePropertyChanged("CreateDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeleteDT {
            get {
                return this.DeleteDTField;
            }
            set {
                if ((this.DeleteDTField.Equals(value) != true)) {
                    this.DeleteDTField = value;
                    this.RaisePropertyChanged("DeleteDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sid {
            get {
                return this.SidField;
            }
            set {
                if ((this.SidField.Equals(value) != true)) {
                    this.SidField = value;
                    this.RaisePropertyChanged("Sid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateDT {
            get {
                return this.UpdateDTField;
            }
            set {
                if ((this.UpdateDTField.Equals(value) != true)) {
                    this.UpdateDTField = value;
                    this.RaisePropertyChanged("UpdateDT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentDTO", Namespace="http://schemas.datacontract.org/2004/07/ActiveLearning.ServiceInterfaces.DTO")]
    [System.SerializableAttribute()]
    public partial class ContentDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseSidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DeleteDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalFileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateDTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseSid {
            get {
                return this.CourseSidField;
            }
            set {
                if ((this.CourseSidField.Equals(value) != true)) {
                    this.CourseSidField = value;
                    this.RaisePropertyChanged("CourseSid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDT {
            get {
                return this.CreateDTField;
            }
            set {
                if ((this.CreateDTField.Equals(value) != true)) {
                    this.CreateDTField = value;
                    this.RaisePropertyChanged("CreateDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeleteDT {
            get {
                return this.DeleteDTField;
            }
            set {
                if ((this.DeleteDTField.Equals(value) != true)) {
                    this.DeleteDTField = value;
                    this.RaisePropertyChanged("DeleteDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalFileName {
            get {
                return this.OriginalFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalFileNameField, value) != true)) {
                    this.OriginalFileNameField = value;
                    this.RaisePropertyChanged("OriginalFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sid {
            get {
                return this.SidField;
            }
            set {
                if ((this.SidField.Equals(value) != true)) {
                    this.SidField = value;
                    this.RaisePropertyChanged("Sid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateDT {
            get {
                return this.UpdateDTField;
            }
            set {
                if ((this.UpdateDTField.Equals(value) != true)) {
                    this.UpdateDTField = value;
                    this.RaisePropertyChanged("UpdateDT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuizQuestionDTO", Namespace="http://schemas.datacontract.org/2004/07/ActiveLearning.ServiceInterfaces.DTO")]
    [System.SerializableAttribute()]
    public partial class QuizQuestionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseSidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DeleteDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ActiveLearning.FormClient.StudentService.QuizOptionDTO[] QuizOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateDTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseSid {
            get {
                return this.CourseSidField;
            }
            set {
                if ((this.CourseSidField.Equals(value) != true)) {
                    this.CourseSidField = value;
                    this.RaisePropertyChanged("CourseSid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDT {
            get {
                return this.CreateDTField;
            }
            set {
                if ((this.CreateDTField.Equals(value) != true)) {
                    this.CreateDTField = value;
                    this.RaisePropertyChanged("CreateDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeleteDT {
            get {
                return this.DeleteDTField;
            }
            set {
                if ((this.DeleteDTField.Equals(value) != true)) {
                    this.DeleteDTField = value;
                    this.RaisePropertyChanged("DeleteDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ActiveLearning.FormClient.StudentService.QuizOptionDTO[] QuizOptions {
            get {
                return this.QuizOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.QuizOptionsField, value) != true)) {
                    this.QuizOptionsField = value;
                    this.RaisePropertyChanged("QuizOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sid {
            get {
                return this.SidField;
            }
            set {
                if ((this.SidField.Equals(value) != true)) {
                    this.SidField = value;
                    this.RaisePropertyChanged("Sid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateDT {
            get {
                return this.UpdateDTField;
            }
            set {
                if ((this.UpdateDTField.Equals(value) != true)) {
                    this.UpdateDTField = value;
                    this.RaisePropertyChanged("UpdateDT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuizOptionDTO", Namespace="http://schemas.datacontract.org/2004/07/ActiveLearning.ServiceInterfaces.DTO")]
    [System.SerializableAttribute()]
    public partial class QuizOptionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DeleteDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuizQuestionSidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateDTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDT {
            get {
                return this.CreateDTField;
            }
            set {
                if ((this.CreateDTField.Equals(value) != true)) {
                    this.CreateDTField = value;
                    this.RaisePropertyChanged("CreateDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeleteDT {
            get {
                return this.DeleteDTField;
            }
            set {
                if ((this.DeleteDTField.Equals(value) != true)) {
                    this.DeleteDTField = value;
                    this.RaisePropertyChanged("DeleteDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCorrect {
            get {
                return this.IsCorrectField;
            }
            set {
                if ((this.IsCorrectField.Equals(value) != true)) {
                    this.IsCorrectField = value;
                    this.RaisePropertyChanged("IsCorrect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuizQuestionSid {
            get {
                return this.QuizQuestionSidField;
            }
            set {
                if ((this.QuizQuestionSidField.Equals(value) != true)) {
                    this.QuizQuestionSidField = value;
                    this.RaisePropertyChanged("QuizQuestionSid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sid {
            get {
                return this.SidField;
            }
            set {
                if ((this.SidField.Equals(value) != true)) {
                    this.SidField = value;
                    this.RaisePropertyChanged("Sid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateDT {
            get {
                return this.UpdateDTField;
            }
            set {
                if ((this.UpdateDTField.Equals(value) != true)) {
                    this.UpdateDTField = value;
                    this.RaisePropertyChanged("UpdateDT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentService.IStudentService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IStudentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/Login", ReplyAction="http://tempuri.org/IStudentService/LoginResponse")]
        bool Login(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/Login", ReplyAction="http://tempuri.org/IStudentService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/Logout", ReplyAction="http://tempuri.org/IStudentService/LogoutResponse")]
        void Logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/Logout", ReplyAction="http://tempuri.org/IStudentService/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetCourses", ReplyAction="http://tempuri.org/IStudentService/GetCoursesResponse")]
        ActiveLearning.FormClient.StudentService.CourseDTO[] GetCourses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetCourses", ReplyAction="http://tempuri.org/IStudentService/GetCoursesResponse")]
        System.Threading.Tasks.Task<ActiveLearning.FormClient.StudentService.CourseDTO[]> GetCoursesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetContentsByCourseSid", ReplyAction="http://tempuri.org/IStudentService/GetContentsByCourseSidResponse")]
        ActiveLearning.FormClient.StudentService.ContentDTO[] GetContentsByCourseSid(int courseSid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetContentsByCourseSid", ReplyAction="http://tempuri.org/IStudentService/GetContentsByCourseSidResponse")]
        System.Threading.Tasks.Task<ActiveLearning.FormClient.StudentService.ContentDTO[]> GetContentsByCourseSidAsync(int courseSid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetNextQuizQuestionByCourseSid", ReplyAction="http://tempuri.org/IStudentService/GetNextQuizQuestionByCourseSidResponse")]
        ActiveLearning.FormClient.StudentService.QuizQuestionDTO GetNextQuizQuestionByCourseSid(int courseSid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetNextQuizQuestionByCourseSid", ReplyAction="http://tempuri.org/IStudentService/GetNextQuizQuestionByCourseSidResponse")]
        System.Threading.Tasks.Task<ActiveLearning.FormClient.StudentService.QuizQuestionDTO> GetNextQuizQuestionByCourseSidAsync(int courseSid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/AnswerQuiz", ReplyAction="http://tempuri.org/IStudentService/AnswerQuizResponse")]
        System.Nullable<bool> AnswerQuiz(int quizQuestionSid, int quizOptionSid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/AnswerQuiz", ReplyAction="http://tempuri.org/IStudentService/AnswerQuizResponse")]
        System.Threading.Tasks.Task<System.Nullable<bool>> AnswerQuizAsync(int quizQuestionSid, int quizOptionSid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServiceChannel : ActiveLearning.FormClient.StudentService.IStudentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<ActiveLearning.FormClient.StudentService.IStudentService>, ActiveLearning.FormClient.StudentService.IStudentService {
        
        public StudentServiceClient() {
        }
        
        public StudentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string userName, string password) {
            return base.Channel.Login(userName, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string userName, string password) {
            return base.Channel.LoginAsync(userName, password);
        }
        
        public void Logout() {
            base.Channel.Logout();
        }
        
        public System.Threading.Tasks.Task LogoutAsync() {
            return base.Channel.LogoutAsync();
        }
        
        public ActiveLearning.FormClient.StudentService.CourseDTO[] GetCourses() {
            return base.Channel.GetCourses();
        }
        
        public System.Threading.Tasks.Task<ActiveLearning.FormClient.StudentService.CourseDTO[]> GetCoursesAsync() {
            return base.Channel.GetCoursesAsync();
        }
        
        public ActiveLearning.FormClient.StudentService.ContentDTO[] GetContentsByCourseSid(int courseSid) {
            return base.Channel.GetContentsByCourseSid(courseSid);
        }
        
        public System.Threading.Tasks.Task<ActiveLearning.FormClient.StudentService.ContentDTO[]> GetContentsByCourseSidAsync(int courseSid) {
            return base.Channel.GetContentsByCourseSidAsync(courseSid);
        }
        
        public ActiveLearning.FormClient.StudentService.QuizQuestionDTO GetNextQuizQuestionByCourseSid(int courseSid) {
            return base.Channel.GetNextQuizQuestionByCourseSid(courseSid);
        }
        
        public System.Threading.Tasks.Task<ActiveLearning.FormClient.StudentService.QuizQuestionDTO> GetNextQuizQuestionByCourseSidAsync(int courseSid) {
            return base.Channel.GetNextQuizQuestionByCourseSidAsync(courseSid);
        }
        
        public System.Nullable<bool> AnswerQuiz(int quizQuestionSid, int quizOptionSid) {
            return base.Channel.AnswerQuiz(quizQuestionSid, quizOptionSid);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<bool>> AnswerQuizAsync(int quizQuestionSid, int quizOptionSid) {
            return base.Channel.AnswerQuizAsync(quizQuestionSid, quizOptionSid);
        }
    }
}
