//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiveLearning.Web.UploadContentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UploadContentService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InstructorSaveContentData", ReplyAction="http://tempuri.org/IService/InstructorSaveContentDataResponse")]
        ActiveLearning.Web.UploadContentService.InstructorSaveContentDataResponse InstructorSaveContentData(ActiveLearning.Web.UploadContentService.InstructorSaveContentDataRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InstructorSaveContentData", ReplyAction="http://tempuri.org/IService/InstructorSaveContentDataResponse")]
        System.Threading.Tasks.Task<ActiveLearning.Web.UploadContentService.InstructorSaveContentDataResponse> InstructorSaveContentDataAsync(ActiveLearning.Web.UploadContentService.InstructorSaveContentDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InstructorReviseContentData", ReplyAction="http://tempuri.org/IService/InstructorReviseContentDataResponse")]
        ActiveLearning.Web.UploadContentService.InstructorReviseContentDataResponse InstructorReviseContentData(ActiveLearning.Web.UploadContentService.InstructorReviseContentDataRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InstructorReviseContentData", ReplyAction="http://tempuri.org/IService/InstructorReviseContentDataResponse")]
        System.Threading.Tasks.Task<ActiveLearning.Web.UploadContentService.InstructorReviseContentDataResponse> InstructorReviseContentDataAsync(ActiveLearning.Web.UploadContentService.InstructorReviseContentDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AdminAcceptContent", ReplyAction="http://tempuri.org/IService/AdminAcceptContentResponse")]
        ActiveLearning.Web.UploadContentService.AdminAcceptContentResponse AdminAcceptContent(ActiveLearning.Web.UploadContentService.AdminAcceptContentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AdminAcceptContent", ReplyAction="http://tempuri.org/IService/AdminAcceptContentResponse")]
        System.Threading.Tasks.Task<ActiveLearning.Web.UploadContentService.AdminAcceptContentResponse> AdminAcceptContentAsync(ActiveLearning.Web.UploadContentService.AdminAcceptContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AdminCommentContent", ReplyAction="http://tempuri.org/IService/AdminCommentContentResponse")]
        ActiveLearning.Web.UploadContentService.AdminCommentContentResponse AdminCommentContent(ActiveLearning.Web.UploadContentService.AdminCommentContentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AdminCommentContent", ReplyAction="http://tempuri.org/IService/AdminCommentContentResponse")]
        System.Threading.Tasks.Task<ActiveLearning.Web.UploadContentService.AdminCommentContentResponse> AdminCommentContentAsync(ActiveLearning.Web.UploadContentService.AdminCommentContentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InstructorSaveContentData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InstructorSaveContentDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int InstructorSid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ActiveLearning.DB.Content Content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int CourseSid;
        
        public InstructorSaveContentDataRequest() {
        }
        
        public InstructorSaveContentDataRequest(int InstructorSid, ActiveLearning.DB.Content Content, int CourseSid) {
            this.InstructorSid = InstructorSid;
            this.Content = Content;
            this.CourseSid = CourseSid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InstructorSaveContentDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InstructorSaveContentDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int ContentSid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool ContentDataSavedSuccessfully;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ContentStatus;
        
        public InstructorSaveContentDataResponse() {
        }
        
        public InstructorSaveContentDataResponse(string Message, int ContentSid, bool ContentDataSavedSuccessfully, string ContentStatus) {
            this.Message = Message;
            this.ContentSid = ContentSid;
            this.ContentDataSavedSuccessfully = ContentDataSavedSuccessfully;
            this.ContentStatus = ContentStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InstructorReviseContentData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InstructorReviseContentDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ActiveLearning.DB.Content Content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int ContentSid;
        
        public InstructorReviseContentDataRequest() {
        }
        
        public InstructorReviseContentDataRequest(ActiveLearning.DB.Content Content, string Message, int ContentSid) {
            this.Content = Content;
            this.Message = Message;
            this.ContentSid = ContentSid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InstructorReviseContentDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InstructorReviseContentDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RevisedSuccessfully;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ContentStatus;
        
        public InstructorReviseContentDataResponse() {
        }
        
        public InstructorReviseContentDataResponse(bool RevisedSuccessfully, string Message, string ContentStatus) {
            this.RevisedSuccessfully = RevisedSuccessfully;
            this.Message = Message;
            this.ContentStatus = ContentStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdminAcceptContent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AdminAcceptContentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ContentSid;
        
        public AdminAcceptContentRequest() {
        }
        
        public AdminAcceptContentRequest(int ContentSid) {
            this.ContentSid = ContentSid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdminAcceptContentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AdminAcceptContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AcceptedSuccessfully;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ContentStatus;
        
        public AdminAcceptContentResponse() {
        }
        
        public AdminAcceptContentResponse(bool AcceptedSuccessfully, string Message, string ContentStatus) {
            this.AcceptedSuccessfully = AcceptedSuccessfully;
            this.Message = Message;
            this.ContentStatus = ContentStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdminCommentContent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AdminCommentContentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ContentSid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Remark;
        
        public AdminCommentContentRequest() {
        }
        
        public AdminCommentContentRequest(int ContentSid, string Remark) {
            this.ContentSid = ContentSid;
            this.Remark = Remark;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdminCommentContentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AdminCommentContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CommentedSuccessfully;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ContentStatus;
        
        public AdminCommentContentResponse() {
        }
        
        public AdminCommentContentResponse(bool CommentedSuccessfully, string Message, string ContentStatus) {
            this.CommentedSuccessfully = CommentedSuccessfully;
            this.Message = Message;
            this.ContentStatus = ContentStatus;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ActiveLearning.Web.UploadContentService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ActiveLearning.Web.UploadContentService.IService>, ActiveLearning.Web.UploadContentService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ActiveLearning.Web.UploadContentService.InstructorSaveContentDataResponse ActiveLearning.Web.UploadContentService.IService.InstructorSaveContentData(ActiveLearning.Web.UploadContentService.InstructorSaveContentDataRequest request) {
            return base.Channel.InstructorSaveContentData(request);
        }
        
        public string InstructorSaveContentData(int InstructorSid, ActiveLearning.DB.Content Content, int CourseSid, out int ContentSid, out bool ContentDataSavedSuccessfully, out string ContentStatus) {
            ActiveLearning.Web.UploadContentService.InstructorSaveContentDataRequest inValue = new ActiveLearning.Web.UploadContentService.InstructorSaveContentDataRequest();
            inValue.InstructorSid = InstructorSid;
            inValue.Content = Content;
            inValue.CourseSid = CourseSid;
            ActiveLearning.Web.UploadContentService.InstructorSaveContentDataResponse retVal = ((ActiveLearning.Web.UploadContentService.IService)(this)).InstructorSaveContentData(inValue);
            ContentSid = retVal.ContentSid;
            ContentDataSavedSuccessfully = retVal.ContentDataSavedSuccessfully;
            ContentStatus = retVal.ContentStatus;
            return retVal.Message;
        }
        
        public System.Threading.Tasks.Task<ActiveLearning.Web.UploadContentService.InstructorSaveContentDataResponse> InstructorSaveContentDataAsync(ActiveLearning.Web.UploadContentService.InstructorSaveContentDataRequest request) {
            return base.Channel.InstructorSaveContentDataAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ActiveLearning.Web.UploadContentService.InstructorReviseContentDataResponse ActiveLearning.Web.UploadContentService.IService.InstructorReviseContentData(ActiveLearning.Web.UploadContentService.InstructorReviseContentDataRequest request) {
            return base.Channel.InstructorReviseContentData(request);
        }
        
        public bool InstructorReviseContentData(ActiveLearning.DB.Content Content, ref string Message, int ContentSid, out string ContentStatus) {
            ActiveLearning.Web.UploadContentService.InstructorReviseContentDataRequest inValue = new ActiveLearning.Web.UploadContentService.InstructorReviseContentDataRequest();
            inValue.Content = Content;
            inValue.Message = Message;
            inValue.ContentSid = ContentSid;
            ActiveLearning.Web.UploadContentService.InstructorReviseContentDataResponse retVal = ((ActiveLearning.Web.UploadContentService.IService)(this)).InstructorReviseContentData(inValue);
            Message = retVal.Message;
            ContentStatus = retVal.ContentStatus;
            return retVal.RevisedSuccessfully;
        }
        
        public System.Threading.Tasks.Task<ActiveLearning.Web.UploadContentService.InstructorReviseContentDataResponse> InstructorReviseContentDataAsync(ActiveLearning.Web.UploadContentService.InstructorReviseContentDataRequest request) {
            return base.Channel.InstructorReviseContentDataAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ActiveLearning.Web.UploadContentService.AdminAcceptContentResponse ActiveLearning.Web.UploadContentService.IService.AdminAcceptContent(ActiveLearning.Web.UploadContentService.AdminAcceptContentRequest request) {
            return base.Channel.AdminAcceptContent(request);
        }
        
        public bool AdminAcceptContent(int ContentSid, out string Message, out string ContentStatus) {
            ActiveLearning.Web.UploadContentService.AdminAcceptContentRequest inValue = new ActiveLearning.Web.UploadContentService.AdminAcceptContentRequest();
            inValue.ContentSid = ContentSid;
            ActiveLearning.Web.UploadContentService.AdminAcceptContentResponse retVal = ((ActiveLearning.Web.UploadContentService.IService)(this)).AdminAcceptContent(inValue);
            Message = retVal.Message;
            ContentStatus = retVal.ContentStatus;
            return retVal.AcceptedSuccessfully;
        }
        
        public System.Threading.Tasks.Task<ActiveLearning.Web.UploadContentService.AdminAcceptContentResponse> AdminAcceptContentAsync(ActiveLearning.Web.UploadContentService.AdminAcceptContentRequest request) {
            return base.Channel.AdminAcceptContentAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ActiveLearning.Web.UploadContentService.AdminCommentContentResponse ActiveLearning.Web.UploadContentService.IService.AdminCommentContent(ActiveLearning.Web.UploadContentService.AdminCommentContentRequest request) {
            return base.Channel.AdminCommentContent(request);
        }
        
        public bool AdminCommentContent(int ContentSid, string Remark, out string Message, out string ContentStatus) {
            ActiveLearning.Web.UploadContentService.AdminCommentContentRequest inValue = new ActiveLearning.Web.UploadContentService.AdminCommentContentRequest();
            inValue.ContentSid = ContentSid;
            inValue.Remark = Remark;
            ActiveLearning.Web.UploadContentService.AdminCommentContentResponse retVal = ((ActiveLearning.Web.UploadContentService.IService)(this)).AdminCommentContent(inValue);
            Message = retVal.Message;
            ContentStatus = retVal.ContentStatus;
            return retVal.CommentedSuccessfully;
        }
        
        public System.Threading.Tasks.Task<ActiveLearning.Web.UploadContentService.AdminCommentContentResponse> AdminCommentContentAsync(ActiveLearning.Web.UploadContentService.AdminCommentContentRequest request) {
            return base.Channel.AdminCommentContentAsync(request);
        }
    }
}
